import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const templates = [
  {
    title: '血糖自我管理评估',
    description: '评估患者在血糖监测、行为管理和自我认知方面的能力，帮助医生了解患者的血糖管理现状。',
    category: 'BLOOD_SUGAR_MANAGEMENT',
    estimatedTime: 5,
    totalScore: 49,
    isSystem: true,
    sortOrder: 1,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一周，您进行血糖监测的天数是？',
        required: true,
        dimension: '血糖监测',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '过去一周，您完成医生建议的每日血糖监测次数的天数是？',
        required: true,
        dimension: '血糖监测',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q3',
        type: 'single_choice',
        title: '过去一周，您按时记录血糖数据的天数是？',
        required: true,
        dimension: '血糖监测',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '您目前的血糖监测频率是？',
        required: true,
        dimension: '行为管理',
        options: [
          { label: '每天3次以上', value: 'more_than_3', score: 5 },
          { label: '每天1-2次', value: '1_to_2', score: 4 },
          { label: '每周3-6次', value: '3_to_6_weekly', score: 3 },
          { label: '每周1-2次', value: '1_to_2_weekly', score: 2 },
          { label: '几乎不测', value: 'rarely', score: 1 },
        ],
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        title: '发现血糖异常时，您通常会怎么做？',
        required: true,
        options: [
          { label: '立即联系医生', value: 'contact_doctor' },
          { label: '自行调整饮食', value: 'adjust_diet' },
          { label: '自行调整药物', value: 'adjust_medication' },
          { label: '记录并等待下次复诊', value: 'record_and_wait' },
          { label: '不做处理', value: 'do_nothing' },
        ],
      },
      {
        id: 'q6',
        type: 'rating',
        title: '您对自己血糖控制目标的了解程度？',
        required: true,
        dimension: '自我认知',
        min: 1,
        max: 5,
        minLabel: '完全不了解',
        maxLabel: '非常了解',
      },
      {
        id: 'q7',
        type: 'single_choice',
        title: '过去一个月，您出现低血糖症状的次数？',
        required: true,
        options: [
          { label: '0次', value: '0' },
          { label: '1-2次', value: '1_2' },
          { label: '3-5次', value: '3_5' },
          { label: '6-10次', value: '6_10' },
          { label: '10次以上', value: 'more_than_10' },
        ],
      },
      {
        id: 'q8',
        type: 'number',
        title: '您目前最新的糖化血红蛋白(HbA1c)值是？',
        required: false,
        min: 4.0,
        max: 15.0,
        unit: '%',
      },
      {
        id: 'q9',
        type: 'multiple_choice',
        title: '您在血糖监测中遇到的最大困难是什么？',
        required: true,
        options: [
          { label: '忘记测量', value: 'forget' },
          { label: '测试疼痛', value: 'pain' },
          { label: '试纸费用高', value: 'cost' },
          { label: '不知道何时测', value: 'dont_know_when' },
          { label: '看不懂结果', value: 'cant_read_results' },
          { label: '其他', value: 'other' },
        ],
      },
      {
        id: 'q10',
        type: 'text',
        title: '您希望医生在血糖管理方面给您什么帮助？',
        required: false,
        maxLength: 200,
      },
    ],
  },
  {
    title: '饮食管理评估',
    description: '评估患者的饮食控制行为和饮食知识水平，为个性化饮食指导提供依据。',
    category: 'DIET_MANAGEMENT',
    estimatedTime: 4,
    totalScore: 36,
    isSystem: true,
    sortOrder: 2,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一周，您按照糖尿病饮食要求合理安排饮食的天数是？',
        required: true,
        dimension: '饮食行为',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '过去一周，您一天内摄入蔬菜水果达5种或以上的天数是？',
        required: true,
        dimension: '饮食行为',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q3',
        type: 'single_choice',
        title: '过去一周，您食用高脂肪/油腻食物的天数是？',
        required: true,
        dimension: '饮食行为',
        options: [
          { label: '0天', value: '0', score: 7 },
          { label: '1天', value: '1', score: 6 },
          { label: '2天', value: '2', score: 5 },
          { label: '3天', value: '3', score: 4 },
          { label: '4天', value: '4', score: 3 },
          { label: '5天', value: '5', score: 2 },
          { label: '6天', value: '6', score: 1 },
          { label: '7天', value: '7', score: 0 },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '您是否掌握碳水化合物计数的方法？',
        required: true,
        dimension: '饮食知识',
        options: [
          { label: '完全掌握', value: 'fully', score: 4 },
          { label: '基本掌握', value: 'mostly', score: 3 },
          { label: '了解一点', value: 'a_little', score: 2 },
          { label: '完全不了解', value: 'not_at_all', score: 1 },
        ],
      },
      {
        id: 'q5',
        type: 'single_choice',
        title: '您每餐的碳水化合物摄入量大约是？',
        required: true,
        options: [
          { label: '<30g', value: 'less_30' },
          { label: '30-50g', value: '30_50' },
          { label: '50-75g', value: '50_75' },
          { label: '75-100g', value: '75_100' },
          { label: '>100g', value: 'more_100' },
          { label: '不清楚', value: 'unknown' },
        ],
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        title: '您通常在什么情况下会出现饮食失控？',
        required: true,
        options: [
          { label: '心情不好时', value: 'bad_mood' },
          { label: '聚餐应酬时', value: 'social_dining' },
          { label: '加班熬夜时', value: 'overtime' },
          { label: '节假日', value: 'holidays' },
          { label: '很少失控', value: 'rarely' },
        ],
      },
      {
        id: 'q7',
        type: 'rating',
        title: '您对自己目前饮食控制的满意度？',
        required: true,
        dimension: '饮食知识',
        min: 1,
        max: 5,
        minLabel: '非常不满意',
        maxLabel: '非常满意',
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        title: '您希望获得哪方面的饮食指导？',
        required: false,
        options: [
          { label: '食谱推荐', value: 'recipes' },
          { label: '碳水计数', value: 'carb_counting' },
          { label: '外出就餐指导', value: 'dining_out' },
          { label: '零食选择', value: 'snack_choices' },
          { label: '其他', value: 'other' },
        ],
      },
    ],
  },
  {
    title: '运动管理评估',
    description: '评估患者的运动习惯和运动安全意识，为制定个性化运动方案提供参考。',
    category: 'EXERCISE_MANAGEMENT',
    estimatedTime: 3,
    totalScore: 21,
    isSystem: true,
    sortOrder: 3,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一周，您进行至少30分钟持续运动（含散步）的天数是？',
        required: true,
        dimension: '运动行为',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '过去一周，您进行中等强度运动（快走、游泳、骑车等）的天数是？',
        required: true,
        dimension: '运动行为',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        title: '您通常在什么时间段运动？',
        required: true,
        options: [
          { label: '早餐前', value: 'before_breakfast' },
          { label: '早餐后', value: 'after_breakfast' },
          { label: '午餐后', value: 'after_lunch' },
          { label: '晚餐前', value: 'before_dinner' },
          { label: '晚餐后', value: 'after_dinner' },
          { label: '不固定', value: 'irregular' },
          { label: '几乎不运动', value: 'rarely' },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '运动前后您是否会监测血糖？',
        required: true,
        dimension: '运动安全',
        options: [
          { label: '每次都测', value: 'always', score: 3 },
          { label: '偶尔测', value: 'sometimes', score: 2 },
          { label: '从不测', value: 'never', score: 1 },
        ],
      },
      {
        id: 'q5',
        type: 'single_choice',
        title: '您在运动中是否遇到过低血糖？',
        required: true,
        options: [
          { label: '从未', value: 'never' },
          { label: '偶尔(1-2次/月)', value: 'occasionally' },
          { label: '经常(>3次/月)', value: 'frequently' },
        ],
      },
      {
        id: 'q6',
        type: 'multiple_choice',
        title: '影响您坚持运动的因素有哪些？',
        required: true,
        options: [
          { label: '时间不够', value: 'no_time' },
          { label: '担心低血糖', value: 'fear_hypo' },
          { label: '身体不适', value: 'discomfort' },
          { label: '天气原因', value: 'weather' },
          { label: '缺乏动力', value: 'no_motivation' },
          { label: '没有合适场地', value: 'no_venue' },
          { label: '其他', value: 'other' },
        ],
      },
    ],
  },
  {
    title: '用药依从性评估',
    description: '评估患者的用药行为和用药知识，帮助医生发现用药问题并提供针对性指导。',
    category: 'MEDICATION_ADHERENCE',
    estimatedTime: 4,
    totalScore: 35,
    isSystem: true,
    sortOrder: 4,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一周，您按医嘱正确使用药物/注射胰岛素的天数是？',
        required: true,
        dimension: '用药行为',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '您是否曾经忘记服药/注射胰岛素？',
        required: true,
        dimension: '用药行为',
        options: [
          { label: '从不', value: 'never', score: 4 },
          { label: '偶尔(每月1-2次)', value: 'occasionally', score: 3 },
          { label: '有时(每周1-2次)', value: 'sometimes', score: 2 },
          { label: '经常(几乎每天)', value: 'frequently', score: 1 },
        ],
      },
      {
        id: 'q3',
        type: 'single_choice',
        title: '当感觉血糖控制良好时，您是否会自行减药或停药？',
        required: true,
        dimension: '用药行为',
        options: [
          { label: '从不', value: 'never', score: 4 },
          { label: '偶尔', value: 'occasionally', score: 3 },
          { label: '有时', value: 'sometimes', score: 2 },
          { label: '经常', value: 'frequently', score: 1 },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '当出现药物副作用时，您通常怎么做？',
        required: true,
        options: [
          { label: '立即联系医生', value: 'contact_doctor' },
          { label: '自行停药', value: 'stop_self' },
          { label: '减量服用', value: 'reduce_dose' },
          { label: '坚持服用并观察', value: 'continue_observe' },
          { label: '不做处理', value: 'do_nothing' },
        ],
      },
      {
        id: 'q5',
        type: 'rating',
        title: '您对目前使用的药物了解程度？',
        required: true,
        dimension: '用药知识',
        min: 1,
        max: 5,
        minLabel: '完全不了解',
        maxLabel: '非常了解',
      },
      {
        id: 'q6',
        type: 'single_choice',
        title: '您是否按规定时间用药（如餐前/餐后）？',
        required: true,
        dimension: '用药行为',
        options: [
          { label: '总是', value: 'always', score: 5 },
          { label: '经常', value: 'often', score: 4 },
          { label: '有时', value: 'sometimes', score: 3 },
          { label: '很少', value: 'rarely', score: 2 },
          { label: '从不', value: 'never', score: 1 },
        ],
      },
      {
        id: 'q7',
        type: 'single_choice',
        title: '您的胰岛素注射部位是否按要求轮换？',
        required: true,
        dimension: '用药行为',
        options: [
          { label: '总是轮换', value: 'always', score: 3 },
          { label: '偶尔轮换', value: 'sometimes', score: 2 },
          { label: '固定部位', value: 'fixed', score: 1 },
          { label: '不注射胰岛素', value: 'not_applicable', score: 0 },
        ],
      },
      {
        id: 'q8',
        type: 'text',
        title: '您在用药方面最困惑的问题是什么？',
        required: false,
        maxLength: 200,
      },
    ],
  },
  {
    title: '生活质量评估',
    description: '从生理、心理、社会和治疗四个维度全面评估糖尿病对患者生活质量的影响。',
    category: 'QUALITY_OF_LIFE',
    estimatedTime: 8,
    totalScore: 75,
    isSystem: true,
    sortOrder: 5,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        title: '糖尿病对您的体力/精力有多大影响？',
        required: true,
        dimension: '生理',
        min: 1,
        max: 5,
        minLabel: '没有影响',
        maxLabel: '影响非常大',
      },
      {
        id: 'q2',
        type: 'rating',
        title: '您是否因糖尿病感到身体不适（口渴、多尿等）？',
        required: true,
        dimension: '生理',
        min: 1,
        max: 5,
        minLabel: '从不',
        maxLabel: '总是',
      },
      {
        id: 'q3',
        type: 'rating',
        title: '糖尿病对您的视力有多大影响？',
        required: true,
        dimension: '生理',
        min: 1,
        max: 5,
        minLabel: '没有影响',
        maxLabel: '影响非常大',
      },
      {
        id: 'q4',
        type: 'rating',
        title: '您是否因糖尿病限制了饮食？',
        required: true,
        dimension: '生理',
        min: 1,
        max: 5,
        minLabel: '没有限制',
        maxLabel: '严重限制',
      },
      {
        id: 'q5',
        type: 'rating',
        title: '您是否因糖尿病减少了运动/体力活动？',
        required: true,
        dimension: '生理',
        min: 1,
        max: 5,
        minLabel: '没有减少',
        maxLabel: '大幅减少',
      },
      {
        id: 'q6',
        type: 'rating',
        title: '您是否为自己的糖尿病感到担忧？',
        required: true,
        dimension: '心理',
        min: 1,
        max: 5,
        minLabel: '完全不担忧',
        maxLabel: '非常担忧',
      },
      {
        id: 'q7',
        type: 'rating',
        title: '您是否因糖尿病感到情绪低落或沮丧？',
        required: true,
        dimension: '心理',
        min: 1,
        max: 5,
        minLabel: '从不',
        maxLabel: '总是',
      },
      {
        id: 'q8',
        type: 'rating',
        title: '您是否担心发生严重的低血糖或并发症？',
        required: true,
        dimension: '心理',
        min: 1,
        max: 5,
        minLabel: '完全不担心',
        maxLabel: '非常担心',
      },
      {
        id: 'q9',
        type: 'rating',
        title: '糖尿病是否让您在饮食方面感到困扰？',
        required: true,
        dimension: '心理',
        min: 1,
        max: 5,
        minLabel: '完全不困扰',
        maxLabel: '非常困扰',
      },
      {
        id: 'q10',
        type: 'rating',
        title: '糖尿病是否影响了您的睡眠质量？',
        required: true,
        dimension: '心理',
        min: 1,
        max: 5,
        minLabel: '完全没有',
        maxLabel: '严重影响',
      },
      {
        id: 'q11',
        type: 'rating',
        title: '糖尿病是否影响了您的工作/学习？',
        required: true,
        dimension: '社会',
        min: 1,
        max: 5,
        minLabel: '完全没有',
        maxLabel: '严重影响',
      },
      {
        id: 'q12',
        type: 'rating',
        title: '糖尿病是否影响了您与家人/朋友的关系？',
        required: true,
        dimension: '社会',
        min: 1,
        max: 5,
        minLabel: '完全没有',
        maxLabel: '严重影响',
      },
      {
        id: 'q13',
        type: 'rating',
        title: '您是否因糖尿病感到被他人区别对待？',
        required: true,
        dimension: '社会',
        min: 1,
        max: 5,
        minLabel: '从不',
        maxLabel: '总是',
      },
      {
        id: 'q14',
        type: 'rating',
        title: '您对目前的治疗方案满意吗？',
        required: true,
        dimension: '治疗',
        min: 1,
        max: 5,
        minLabel: '非常满意',
        maxLabel: '非常不满意',
        reverseScore: true,
      },
      {
        id: 'q15',
        type: 'rating',
        title: '您对自己整体的血糖控制满意吗？',
        required: true,
        dimension: '治疗',
        min: 1,
        max: 5,
        minLabel: '非常满意',
        maxLabel: '非常不满意',
        reverseScore: true,
      },
    ],
  },
  {
    title: '低血糖风险评估',
    description: '评估患者低血糖发生频率、识别能力和应急处理水平，帮助医生识别高风险患者。',
    category: 'HYPOGLYCEMIA_RISK',
    estimatedTime: 4,
    totalScore: 0,
    isSystem: true,
    sortOrder: 6,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一个月，您发生低血糖（血糖<3.9mmol/L）的次数？',
        required: true,
        options: [
          { label: '0次', value: '0' },
          { label: '1-2次', value: '1_2' },
          { label: '3-5次', value: '3_5' },
          { label: '6-10次', value: '6_10' },
          { label: '>10次', value: 'more_than_10' },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '过去一个月，您是否发生过严重低血糖（需要他人协助）？',
        required: true,
        options: [
          { label: '没有', value: 'none' },
          { label: '1次', value: '1' },
          { label: '2次', value: '2' },
          { label: '>2次', value: 'more_than_2' },
        ],
      },
      {
        id: 'q3',
        type: 'multiple_choice',
        title: '低血糖通常发生在什么时间？',
        required: true,
        options: [
          { label: '凌晨', value: 'early_morning' },
          { label: '早餐前', value: 'before_breakfast' },
          { label: '上午', value: 'morning' },
          { label: '午餐前', value: 'before_lunch' },
          { label: '下午', value: 'afternoon' },
          { label: '晚餐前', value: 'before_dinner' },
          { label: '睡前', value: 'before_sleep' },
          { label: '运动时', value: 'during_exercise' },
          { label: '不确定', value: 'uncertain' },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '您能否识别低血糖的早期症状？',
        required: true,
        options: [
          { label: '总是能', value: 'always' },
          { label: '大多数时候能', value: 'mostly' },
          { label: '有时能', value: 'sometimes' },
          { label: '很难识别', value: 'rarely' },
        ],
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        title: '发生低血糖时您通常如何处理？',
        required: true,
        options: [
          { label: '吃糖果', value: 'candy' },
          { label: '喝含糖饮料', value: 'sugary_drink' },
          { label: '吃饼干面包', value: 'biscuit_bread' },
          { label: '服用葡萄糖片', value: 'glucose_tablet' },
          { label: '等待自行恢复', value: 'wait' },
          { label: '寻求帮助', value: 'seek_help' },
        ],
      },
      {
        id: 'q6',
        type: 'single_choice',
        title: '您是否随身携带应急糖果/葡萄糖？',
        required: true,
        options: [
          { label: '总是', value: 'always' },
          { label: '经常', value: 'often' },
          { label: '偶尔', value: 'sometimes' },
          { label: '从不', value: 'never' },
        ],
      },
      {
        id: 'q7',
        type: 'rating',
        title: '低血糖对您日常生活的影响程度？',
        required: true,
        min: 1,
        max: 5,
        minLabel: '无影响',
        maxLabel: '严重影响',
      },
      {
        id: 'q8',
        type: 'multiple_choice',
        title: '您认为导致低血糖的主要原因是？',
        required: true,
        options: [
          { label: '药物剂量过大', value: 'overdose' },
          { label: '进食不规律', value: 'irregular_meals' },
          { label: '运动过量', value: 'excessive_exercise' },
          { label: '饮酒', value: 'alcohol' },
          { label: '不清楚', value: 'unknown' },
          { label: '其他', value: 'other' },
        ],
      },
    ],
  },
  {
    title: '足部护理评估',
    description: '评估患者的足部自我护理行为和足部健康状况，预防糖尿病足并发症。',
    category: 'FOOT_CARE',
    estimatedTime: 3,
    totalScore: 30,
    isSystem: true,
    sortOrder: 7,
    questions: [
      {
        id: 'q1',
        type: 'single_choice',
        title: '过去一周，您仔细检查脚部是否有问题的天数是？',
        required: true,
        dimension: '足部护理',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q2',
        type: 'single_choice',
        title: '过去一周，您穿鞋前检查鞋子内部的天数是？',
        required: true,
        dimension: '足部护理',
        options: [
          { label: '0天', value: '0', score: 0 },
          { label: '1天', value: '1', score: 1 },
          { label: '2天', value: '2', score: 2 },
          { label: '3天', value: '3', score: 3 },
          { label: '4天', value: '4', score: 4 },
          { label: '5天', value: '5', score: 5 },
          { label: '6天', value: '6', score: 6 },
          { label: '7天', value: '7', score: 7 },
        ],
      },
      {
        id: 'q3',
        type: 'single_choice',
        title: '您是否每天用温水洗脚并擦干趾间？',
        required: true,
        dimension: '足部护理',
        options: [
          { label: '每天', value: 'daily', score: 4 },
          { label: '大多数时候', value: 'mostly', score: 3 },
          { label: '偶尔', value: 'sometimes', score: 2 },
          { label: '从不', value: 'never', score: 1 },
        ],
      },
      {
        id: 'q4',
        type: 'single_choice',
        title: '您是否穿合适的鞋袜？',
        required: true,
        dimension: '足部护理',
        options: [
          { label: '总是', value: 'always', score: 4 },
          { label: '经常', value: 'often', score: 3 },
          { label: '偶尔', value: 'sometimes', score: 2 },
          { label: '从不', value: 'never', score: 1 },
        ],
      },
      {
        id: 'q5',
        type: 'multiple_choice',
        title: '您的脚部目前是否有以下问题？',
        required: true,
        options: [
          { label: '皮肤干裂', value: 'dry_cracked' },
          { label: '水泡', value: 'blisters' },
          { label: '红肿', value: 'swelling' },
          { label: '溃疡', value: 'ulcer' },
          { label: '甲沟炎', value: 'paronychia' },
          { label: '麻木', value: 'numbness' },
          { label: '疼痛', value: 'pain' },
          { label: '无问题', value: 'none' },
        ],
      },
      {
        id: 'q6',
        type: 'single_choice',
        title: '您最近一次足部专科检查是什么时候？',
        required: true,
        options: [
          { label: '1个月内', value: 'within_1_month' },
          { label: '1-3个月', value: '1_3_months' },
          { label: '3-6个月', value: '3_6_months' },
          { label: '6-12个月', value: '6_12_months' },
          { label: '>1年', value: 'more_than_1_year' },
          { label: '从未检查', value: 'never' },
        ],
      },
    ],
  },
  {
    title: '心理状态评估',
    description: '评估患者因糖尿病产生的心理困扰程度，帮助医生及时发现心理问题并提供支持。',
    category: 'MENTAL_HEALTH',
    estimatedTime: 5,
    totalScore: 50,
    isSystem: true,
    sortOrder: 8,
    questions: [
      {
        id: 'q1',
        type: 'rating',
        title: '对糖尿病的未来感到恐惧？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q2',
        type: 'rating',
        title: '对自己的糖尿病治疗方案感到不满？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q3',
        type: 'rating',
        title: '对自己是否能管理好糖尿病感到怀疑？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q4',
        type: 'rating',
        title: '不被周围人理解自己的糖尿病？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q5',
        type: 'rating',
        title: '感到孤独面对糖尿病？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q6',
        type: 'rating',
        title: '因控糖而对日常饮食感到厌烦？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q7',
        type: 'rating',
        title: '对频繁注射/服药感到疲倦？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q8',
        type: 'rating',
        title: '糖尿病让您产生焦虑或抑郁情绪？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q9',
        type: 'rating',
        title: '担心低血糖带来的安全风险？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
      {
        id: 'q10',
        type: 'rating',
        title: '感觉糖尿病夺走了生活中的乐趣？',
        required: true,
        dimension: '心理困扰',
        min: 1,
        max: 5,
        minLabel: '完全不是问题',
        maxLabel: '非常严重的问题',
      },
    ],
  },
]

async function main() {
  console.log('Seeding questionnaire templates...')

  await prisma.questionnaireTemplate.deleteMany({
    where: { isSystem: true },
  })

  for (const template of templates) {
    await prisma.questionnaireTemplate.create({
      data: {
        title: template.title,
        description: template.description,
        category: template.category as any,
        estimatedTime: template.estimatedTime,
        totalScore: template.totalScore,
        isSystem: template.isSystem,
        sortOrder: template.sortOrder,
        questions: template.questions,
      },
    })
  }

  console.log('Questionnaire seed data created successfully! (8 templates)')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
